#!/usr/bin/env bash
# Evaluate one model on one metric.  Everything is configured in
# tool_unlearn/eval_config.sh -- edit that, then just run:
#
#     ./tool_unlearn/evaluate.sh
#
# or override a single knob inline:
#
#     METRIC=T_r ./tool_unlearn/evaluate.sh
#     MODEL_UNDER_TEST=/path/to/other/ckpt METRIC=T_T ./tool_unlearn/evaluate.sh
#
# It starts the fake API server on the right data file, runs the agent, judges
# the trajectories and prints Procedure / Response / T_T.
set -uo pipefail
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT"

# Inline overrides win over the config file.
_over=$(for v in MODEL_UNDER_TEST METRIC MODE PLANNER_MODEL COLLAB_COND \
                 SINGLE_GPU COLLAB_GPUS API_BASE API_KEY SIMULATOR_MODEL \
                 JUDGE_MODEL JUDGE_WORKERS SIM_PORT OUT_DIR API_FILE; do
          [ -n "${!v+x}" ] && printf '%s=%q\n' "$v" "${!v}"
        done)
source tool_unlearn/eval_config.sh
eval "$_over"

TA_PY=${TA_PY:-/home/public/wenxian/ToolAlpaca/.venv/bin/python}
export PYTHONPATH=${TA_EXTRA_PKGS:-/home/wenxian/wenxian/toolalpaca_extra_pkgs}:$ROOT
export OPENAI_API_BASE=$API_BASE
export OPENAI_API_KEY=$API_KEY
# The endpoint is not reachable through a proxy and the simulator is on
# localhost; leaving these set makes both fail in confusing ways.
unset http_proxy https_proxy HTTP_PROXY HTTPS_PROXY all_proxy ALL_PROXY
export no_proxy='*' NO_PROXY='*'

# Which data file backs this metric.  T_T uses APIs the model has never seen;
# T_f / T_r use held-out demonstrations of the training tools, generated by
# prepare_data.py.
case "$METRIC" in
  T_T) DEFAULT_API=./data/eval_simulated.json ;;
  T_f) DEFAULT_API=./tool_unlearn/data/forget_eval_api.json ;;
  T_r) DEFAULT_API=./tool_unlearn/data/retain_eval_api.json ;;
  *)   echo "METRIC must be T_T, T_f or T_r (got '$METRIC')"; exit 1 ;;
esac
API_FILE=${API_FILE:-$DEFAULT_API}
[ -f "$API_FILE" ] || { echo "missing $API_FILE -- run prepare_data.py first"; exit 1; }
[ -d "$MODEL_UNDER_TEST" ] || { echo "MODEL_UNDER_TEST is not a directory: $MODEL_UNDER_TEST"; exit 1; }

TAG="${METRIC}_${MODE}_$(basename "$MODEL_UNDER_TEST")"
mkdir -p "$OUT_DIR" logs

# ---------------------------------------------------------------- simulator
echo "[eval] starting the API simulator on port $SIM_PORT ($(basename "$API_FILE"))"
OPENAI_DEFAULT_MODEL=$SIMULATOR_MODEL nohup $TA_PY instance_generation/simulator.py \
    -api "$API_FILE" --port "$SIM_PORT" --model "$SIMULATOR_MODEL" > "logs/sim_${TAG}.log" 2>&1 &
SIM_PID=$!
trap 'kill $SIM_PID 2>/dev/null' EXIT
for _ in $(seq 1 60); do
  curl -s --noproxy '*' -m 2 "http://127.0.0.1:$SIM_PORT/docs" -o /dev/null && break
  sleep 2
done
curl -s --noproxy '*' -m 2 "http://127.0.0.1:$SIM_PORT/docs" -o /dev/null \
  || { echo "simulator failed to start; see logs/sim_${TAG}.log"; exit 1; }

# ----------------------------------------------------------------- rollout
export ACTOR_MODEL=$MODEL_UNDER_TEST
export OPENAI_DEFAULT_MODEL=$SIMULATOR_MODEL
GEN=$OUT_DIR/${TAG}.json

if [ "$MODE" = "single" ]; then
  export CUDA_VISIBLE_DEVICES=$SINGLE_GPU
  export ACTOR_DEVICE=0
  COND=B0
else
  # COLLAB_LAYOUT=single: 13B (whole, fp16) + 7B actor on ONE card, so the two
  # collab runs can go in parallel on the two GPUs.  split (default): 13B sharded
  # 20/6 across both cards with the actor on the 2nd.
  export PLANNER_MODEL
  if [ "${COLLAB_LAYOUT:-split}" = "single" ]; then
    export CUDA_VISIBLE_DEVICES=$SINGLE_GPU
    export ACTOR_DEVICE=0
    export COLLAB_LAYOUT=single
  else
    export CUDA_VISIBLE_DEVICES=$COLLAB_GPUS
    export ACTOR_DEVICE=1            # actor on the 2nd card; 13B fills the 1st
    export COLLAB_LAYOUT=split
  fi
  COND=$COLLAB_COND
fi

echo "[eval] $METRIC | $MODE | actor=$MODEL_UNDER_TEST | condition=$COND"
$TA_PY harness/run_toolalpaca.py --condition "$COND" \
    -api "$API_FILE" --server_url "http://127.0.0.1:$SIM_PORT" \
    --offset "${OFFSET:-0}" --length "${LENGTH:--1}" --instruction_offset 0 --instruction_length -1 \
    -out "$OUT_DIR" 2>&1 | grep -viE "futurewarning|torch.load|Token indices" || exit 1
mv "$OUT_DIR/${COND}.json" "$GEN"
[ -f "$OUT_DIR/${COND}_trace.json" ] && mv "$OUT_DIR/${COND}_trace.json" "$OUT_DIR/${TAG}_trace.json"

# ------------------------------------------------------------------- judge
echo "[eval] judging with $JUDGE_MODEL"
JUD=$OUT_DIR/${TAG}_judge.json
RESUME=""; [ -f "$JUD" ] && RESUME="--continue_run"
OPENAI_DEFAULT_MODEL=$JUDGE_MODEL $TA_PY evaluation.py \
    -api "$GEN" -out "$JUD" --judge_model "$JUDGE_MODEL" \
    --num_workers "$JUDGE_WORKERS" $RESUME || exit 1

$TA_PY -c "
import json
s = json.load(open('$JUD'))['statistics']; n = s['num']
print()
print('=== $METRIC | $MODE | $(basename "$MODEL_UNDER_TEST") ===')
print('  Procedure %.1f   Response %.1f   Overall %.1f   (errors %d, n %d)'
      % (100*s['process']['Yes']/n, 100*s['response']['Yes']/n,
         100*s['both']/n, s['error_num'], n))
print('  -> $JUD')"
